spring:
  application:
    name: authorize
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:mem:nubank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false


control-interval-transaction:
  minute: 2
  count: 3